export const styles = {
    appContainer: {
      backgroundColor: 'black',
      height: '100vh',
      width: '100vw',
      color: 'white',
      fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif',
      overflow: 'hidden',
    },
    contentArea: {
      height: '100%',
      width: '100%',
      overflowY: 'auto',
    },
    searchContainer: {
      width: '95%',
      display: 'flex',
      gap: '10px',
      marginBottom: '20px',
      justifyContent: 'center',
    },
    searchInput: {
      padding: '12px',
      borderRadius: '8px',
      border: '1px solid #444',
      backgroundColor: '#222',
      color: 'white',
      width: '70%',
      fontSize: '16px',
    },
    searchBtn: {
      padding: '12px 20px',
      borderRadius: '8px',
      border: 'none',
      backgroundColor: '#00f2ea',
      color: 'black',
      fontWeight: 'bold',
      cursor: 'pointer',
    },
    searchResultLabel: {
        width: '100%', 
        textAlign: 'center', 
        color: '#888', 
        fontSize: '14px', 
        marginBottom: '10px'
    },
    // --- Автоскролл (Плавающее меню справа) ---
    autoScrollPanel: {
        position: 'fixed',
        top: '20%',
        right: '10px',
        zIndex: 50,
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'flex-end',
        gap: '10px',
    },
    autoScrollBtn: {
        width: '50px',
        height: '50px',
        borderRadius: '50%',
        border: 'none',
        color: 'black', // Цвет иконки
        fontSize: '24px',
        cursor: 'pointer',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        boxShadow: '0 2px 5px rgba(0,0,0,0.5)',
        transition: 'all 0.3s',
    },
    timerInput: {
        width: '40px',
        height: '40px',
        borderRadius: '20px',
        border: 'none',
        textAlign: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.6)',
        color: 'white',
        fontSize: '14px',
        outline: 'none',
        backdropFilter: 'blur(4px)',
    },

    // --- Категории (Боковая панель) ---
    categorySidebar: {
        position: 'fixed',
        top: 0,
        left: 0,
        height: '100vh',
        width: '200px', // Ширина панели
        backgroundColor: 'rgba(20, 20, 20, 0.95)',
        paddingTop: '60px', // Отступ сверху
        paddingLeft: '10px',
        zIndex: 90,
        transition: 'transform 0.3s ease',
        borderRight: '1px solid #333',
        overflowY: 'auto'
    },
    categoryToggleBtn: {
        position: 'fixed',
        top: '15px',
        left: '15px',
        zIndex: 100, // Поверх всего
        background: '#333',
        color: 'white',
        border: 'none',
        padding: '8px 12px',
        borderRadius: '8px',
        cursor: 'pointer',
    },
    categoryItem: {
        padding: '12px 10px',
        cursor: 'pointer',
        color: '#ccc',
        borderBottom: '1px solid #333',
        fontSize: '14px',
    },
    activeCategory: {
        color: '#00f2ea',
        fontWeight: 'bold',
        paddingLeft: '15px', // Сдвиг активной
    },
    
    // --- Лента ---
    feedContainer: {
      height: '100vh',
      width: '100%',
      overflowY: 'scroll',
      scrollSnapType: 'y mandatory',
      scrollBehavior: 'smooth',
    },
    feedItem: {
      height: '100vh',
      width: '100%',
      scrollSnapAlign: 'start',
      position: 'relative',
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: '#000',
    },
    feedImage: {
      width: '100%',
      height: '100%',
      objectFit: 'contain',
      backgroundColor: '#111',
    },
    feedOverlay: {
      position: 'absolute',
      bottom: '80px',
      left: '10px',
      textShadow: '1px 1px 2px black',
      backgroundColor: 'rgba(0,0,0,0.3)',
      padding: '10px',
      borderRadius: '8px',
      maxWidth: '80%',
    },
    centerMsg: {
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'center',
      alignItems: 'center',
      height: '100vh',
      textAlign: 'center',
    },
    // --- Галереи ---
    galleryContainer: {
      paddingTop: '20px',
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
    },
    grid: {
      display: 'grid',
      gridTemplateColumns: 'repeat(auto-fill, minmax(110px, 1fr))',
      gap: '8px',
      width: '95%',
      paddingBottom: '20px'
    },
    card: {
      position: 'relative',
      aspectRatio: '2/3',
      backgroundColor: '#333',
      borderRadius: '8px',
      overflow: 'hidden',
    },
    gridImage: {
      width: '100%',
      height: '100%',
      objectFit: 'cover',
    },
    checkMark: {
      position: 'absolute',
      top: '5px',
      right: '5px',
      background: '#00f2ea',
      color: '#000',
      borderRadius: '50%',
      width: '20px',
      height: '20px',
      textAlign: 'center',
      lineHeight: '20px',
      fontSize: '14px',
      fontWeight: 'bold',
    },
    loadBtn: {
      padding: '10px 30px',
      background: '#333',
      color: '#fff',
      border: 'none',
      borderRadius: '20px',
      marginBottom: '20px'
    },
    // --- Меню ---
    navBar: {
      position: 'fixed',
      bottom: 0,
      left: 0,
      width: '100%',
      height: '60px',
      backgroundColor: 'rgba(0,0,0, 0.9)',
      borderTop: '1px solid #333',
      display: 'flex',
      justifyContent: 'space-around',
      alignItems: 'center',
      zIndex: 1000,
    },
    navBtn: {
      background: 'none',
      border: 'none',
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'center',
      cursor: 'pointer',
      width: '50%',
      height: '100%',
    }
  };